### ISSUE TITLE
Imagen al realizar reserva

### ISSUE THREAD

**Issue by castromaciel** [djauguust/Grupo2-TP3-Front-Restaurant-RollingCode#12]
## Proceso

1. Iniciar sesión
2. Realizar una reserva

## Resultado esperado

Si una imagen no carga correctamente, visualizar un texto alternativo

## Resultado actual

No presenta la imagen, ni el texto alternativo

## Captura

<img width="1434" alt="image" src="https://github.com/djauguust/Grupo2-TP3-Back-Restaurant-RollingCode/assets/83432755/7ca838f3-0d02-41df-b5fb-bd29c66cf2fe">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Yudi454** [comment]
Lo solucione cambiando el link de la imagen, porque antes venia del trello y ahora viene de la página donde subimos las imágenes. El error de la imagen lo solucione en el commit 3537399 y le agregue un texto alternativo en el commit dad0528.
