### ISSUE TITLE
Login - Inputs

### ISSUE THREAD

**Issue by castromaciel** [djauguust/Grupo2-TP3-Front-Restaurant-RollingCode#13]
## Proceso

1. Ir a Login

## Resultado actual

Los Inputs no deberían desbordar el contenedor

## Captura

<img width="325" alt="image" src="https://github.com/djauguust/Grupo2-TP3-Front-Restaurant-RollingCode/assets/83432755/ee5fcd6b-223b-446d-b237-be58bbdcf97b">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by djauguust** [comment]
![image](https://github.com/djauguust/Grupo2-TP3-Front-Restaurant-RollingCode/assets/57671434/a583650b-c06c-44fe-bac6-49f97be835c4)

Utilizando la librería de bootstrap, pudimos corregir el error de que los inputs no se salgan del contenedor.
