### ISSUE TITLE
Eliminar Logs en consola

### ISSUE THREAD

**Issue by castromaciel** [djauguust/Grupo2-TP3-Front-Restaurant-RollingCode#14]
## Proceso

1. Iniciar sesión
2. Ver detalles de un usuario

## Resultado esperado

No deberían aparecer logs en la consola.

## Resultado actual

Una posible solución, si se quiere informar algo es mostrarlo por un mensaje (Como se presenta actualmente)

## Captura

<img width="1439" alt="image" src="https://github.com/djauguust/Grupo2-TP3-Front-Restaurant-RollingCode/assets/83432755/d0fd1d39-c577-4a03-b21a-e66805c10719">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Yudi454** [comment]
Solucione el error de los logs cambiándolos por un toast, asi cuando salte uno lo haga como toast. El error lo solucione en el commit 035872d.
