### ISSUE TITLE
Admin - Modificar datos del restaurante

### ISSUE THREAD

**Issue by castromaciel** [djauguust/Grupo2-TP3-Front-Restaurant-RollingCode#15]
## Proceso

1. Iniciar sesión como admin
2. Modificar los datos del restaurante

## Resultado esperado

Al diligenciar el formulario con cambios para el restaurante, se esperan ver los cambios reflejados

## Resultado actual

Actualmente no sucede nada, y se muestra un error en consola

## Captura

<img width="1437" alt="image" src="https://github.com/djauguust/Grupo2-TP3-Back-Restaurant-RollingCode/assets/83432755/b15b2735-dc58-4966-985d-4e9433f3d0f7">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Yudi454** [comment]
El error era porque usamos react-datepicker para los inputs del horario del restaurante y no enviaba la hora en formato number, lo solucione formateando el valor del input a un formato HH:mm (ej: 12:00), con un replace cambie los : por un espacio vacio y con el parseInt lo pase a formato number, lo solucione en el commit 3e27448.
